#!/bin/bash
set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info()  { echo -e "${GREEN}[FILWIZARD]${NC} $1"; }
log_warn()  { echo -e "${YELLOW}[FILWIZARD]${NC} $1"; }
log_error() { echo -e "${RED}[FILWIZARD]${NC} $1" >&2; }

wait_for_file() {
    local file="$1" desc="$2"
    log_info "Waiting for $desc..."
    while [ ! -f "$file" ] || [ ! -s "$file" ]; do sleep 2; done
    log_info "$desc found"
}

# ── Config ──
FILECOIN_RPC="http://lotus0:1234/rpc/v1"
ETH_RPC_URL="http://lotus0:1234/rpc/v1"
RPC_WS_URL="ws://lotus0:1234/rpc/v1"
RPC_LOTUS="${RPC_LOTUS:-http://lotus0:1234/rpc/v0}"
CHAIN_ID="31415926"
INIT_BLOCK_HEIGHT=5

WORKSPACE_PATH="/opt/filwizard/workspace"
CONFIG_PATH="/opt/filwizard/config/filecoin-synapse.json"
ENV_OUTPUT="/shared/environment.env"
CURIO_SHARED_DIR="/shared/curio"
CURIO_ENV_FILE="${CURIO_SHARED_DIR}/.env.curio"
ACCOUNTS_FILE="${WORKSPACE_PATH}/accounts.json"

SP_SERVICE_URL="${SP_SERVICE_URL:-http://curio:80}"
SP_NAME="${SP_NAME:-My Devnet Provider}"
SP_DESCRIPTION="${SP_DESCRIPTION:-Devnet provider for Warm Storage}"

# ── 1. Wait for chain ──
log_info "Waiting for block height ${INIT_BLOCK_HEIGHT}..."
BLOCK_HEIGHT_REACHED=0
while [ "${INIT_BLOCK_HEIGHT}" -gt "${BLOCK_HEIGHT_REACHED}" ]; do
    RESPONSE=$(curl -s --max-time 5 -X POST "$RPC_LOTUS" \
        -H 'Content-Type: application/json' \
        --data '{"jsonrpc":"2.0","id":1,"method":"Filecoin.ChainHead","params":[]}' 2>/dev/null || echo '{}')
    BLOCK_HEIGHT_REACHED=$(echo "$RESPONSE" | jq -r '.result.Height // 0' 2>/dev/null)
    [ -z "$BLOCK_HEIGHT_REACHED" ] || [ "$BLOCK_HEIGHT_REACHED" = "null" ] && BLOCK_HEIGHT_REACHED=0
    [ "${INIT_BLOCK_HEIGHT}" -le "${BLOCK_HEIGHT_REACHED}" ] && break
    log_info "Height: ${BLOCK_HEIGHT_REACHED}, waiting..."
    sleep 5
done
log_info "Chain ready at height ${BLOCK_HEIGHT_REACHED}"

# ── 2. Setup Filecoin env ──
JWT_FILE="/shared/lotus0/lotus0-jwt"
wait_for_file "$JWT_FILE" "Lotus JWT"
export FILECOIN_RPC ETH_RPC_URL
export FILECOIN_TOKEN=$(cat "$JWT_FILE")

# ── 3. Deploy FOC contracts ──
log_info "Deploying contracts via FilWizard..."
cd /opt/filwizard

filwizard contract deploy-local \
    --config "$CONFIG_PATH" \
    --workspace "$WORKSPACE_PATH" \
    --rpc-url "$FILECOIN_RPC" \
    --create-deployer \
    --bindings \
    || log_warn "Deployment completed with warnings, continuing..."

wait_for_file "${WORKSPACE_PATH}/deployments.json" "deployments.json"

# ── 4. Export environment (simple bash + jq) ──
log_info "Exporting environment..."
bash /opt/filwizard/scripts/export-environment.sh \
    "$WORKSPACE_PATH" \
    "$ENV_OUTPUT" \
    "$CHAIN_ID" \
    "$FILECOIN_RPC" \
    "$RPC_WS_URL"

log_info "environment.env written to $ENV_OUTPUT"

# ── 5. Create Curio .env (subset with CURIO_ prefix) ──
log_info "Creating Curio environment file..."
mkdir -p "$CURIO_SHARED_DIR"

# Source the exported env to get address variables
set -a
source "$ENV_OUTPUT"
set +a

cat > "$CURIO_ENV_FILE" << EOF
# Curio Devnet Contract Addresses
# Generated by filwizard entrypoint

CURIO_DEVNET_PDP_VERIFIER_ADDRESS=${PDP_VERIFIER_PROXY_ADDRESS}
CURIO_DEVNET_FWSS_ADDRESS=${FWSS_PROXY_ADDRESS}
CURIO_DEVNET_SERVICE_REGISTRY_ADDRESS=${SERVICE_PROVIDER_REGISTRY_PROXY_ADDRESS}
CURIO_DEVNET_PAYMENTS_ADDRESS=${FILECOIN_PAY_ADDRESS}
CURIO_DEVNET_USDFC_ADDRESS=${USDFC_ADDRESS}
CURIO_DEVNET_MULTICALL_ADDRESS=${MULTICALL3_ADDRESS}
EOF

log_info "Curio env created: $CURIO_ENV_FILE"

# ── 6. Create client wallet ──
log_info "Creating client wallet..."
filwizard wallet create \
    --type ethereum \
    --count 1 \
    --fund 5 \
    --show-private-key \
    --key-output "$ACCOUNTS_FILE" \
    --name "client"

CLIENT_PRIVATE_KEY=$(jq -r '.accounts.client.privateKey' "$ACCOUNTS_FILE")
DEPLOYER_PRIVATE_KEY=$(jq -r '.accounts.deployer.privateKey' "$ACCOUNTS_FILE")

# ── 7. Wait for Curio SP private key ──
SP_PRIVATE_KEY_FILE="/shared/curio/private_key"
wait_for_file "$SP_PRIVATE_KEY_FILE" "SP private key from Curio"
SP_PRIVATE_KEY=$(cat "$SP_PRIVATE_KEY_FILE" | tr -d '[:space:]')

# ── 8. Mint tokens ──
log_info "Minting tokens..."

filwizard payments mint-private-key --workspace "$WORKSPACE_PATH" \
    --private-key "$CLIENT_PRIVATE_KEY" --amount 1000000000000000000000 --fil 0

filwizard payments mint-private-key --workspace "$WORKSPACE_PATH" \
    --private-key "$CLIENT_PRIVATE_KEY" --amount 0 --fil 10

filwizard payments mint-private-key --workspace "$WORKSPACE_PATH" \
    --private-key "$SP_PRIVATE_KEY" --amount 10000000000000000000000 --fil 0

filwizard payments mint-private-key --workspace "$WORKSPACE_PATH" \
    --private-key "$SP_PRIVATE_KEY" --amount 0 --fil 10

log_info "Tokens minted"

# ── 9. Register service provider ──
log_info "Registering service provider..."

export DEPLOYER_PRIVATE_KEY SP_PRIVATE_KEY CLIENT_PRIVATE_KEY
export SP_SERVICE_URL SP_NAME SP_DESCRIPTION

node /opt/filwizard/scripts/register-service-provider.js \
    --rpc-url "$FILECOIN_RPC" \
    --warm-storage "$FWSS_PROXY_ADDRESS" \
    --sp-registry "$SERVICE_PROVIDER_REGISTRY_PROXY_ADDRESS"

log_info "Service provider registered"

# ── 10. Add approved provider to warm storage ──
log_info "Adding service provider to warm storage global whitelist..."

export DEPLOYER_PRIVATE_KEY SP_PRIVATE_KEY

node /opt/filwizard/scripts/warm-add.js \
    --rpc-url "$FILECOIN_RPC" \
    --warm-storage "$FWSS_PROXY_ADDRESS" \
    --sp-registry "$SERVICE_PROVIDER_REGISTRY_PROXY_ADDRESS"

log_info "Service provider added to global whitelist (ready for dapps)"

# ── 11. Signal healthy ──
log_info "FilWizard setup complete. Signaling healthy."
touch /tmp/healthy

# Keep container alive (compose healthcheck will gate dependents)
sleep infinity
