#!/bin/bash
set -e

# Simple environment export using bash + jq
# Replaces the FilWizard env export command

WORKSPACE="${1:-/opt/filwizard/workspace}"
OUTPUT="${2:-/shared/environment.env}"
CHAIN_ID="${3:-31415926}"
RPC_URL="${4:-http://lotus0:1234/rpc/v1}"
RPC_WS_URL="${5:-ws://lotus0:1234/rpc/v1}"

# Use service contracts from workspace deployment (already deployed)
SERVICE_CONTRACTS_JSON="$WORKSPACE/filecoinwarmstorage/service_contracts/deployments.json"
WORKSPACE_DEPLOYMENTS_JSON="$WORKSPACE/deployments.json"
ACCOUNTS_JSON="$WORKSPACE/accounts.json"

# Write to file instead of stdout
{
echo "# Generated by filwizard environment export"
echo "# Timestamp: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo ""
echo "# Network"
echo "CHAIN_ID=$CHAIN_ID"
echo "RPC_URL=$RPC_URL"
echo "ETH_RPC_URL=$RPC_URL"
echo "RPC_WS_URL=$RPC_WS_URL"
echo ""

# Service contract addresses (from workspace deployment)
echo "# Service Contract Addresses"
if [ -f "$SERVICE_CONTRACTS_JSON" ]; then
    jq -r --arg chain "$CHAIN_ID" '
        .[$chain] // {} |
        to_entries |
        map(select(.key != "metadata")) |
        sort_by(.key) |
        .[] |
        "\(.key)=\(.value)"
    ' "$SERVICE_CONTRACTS_JSON"
else
    echo "# Note: Service contracts will be loaded after deployment"
fi

# USDFC and Multicall3 from workspace
if [ -f "$WORKSPACE_DEPLOYMENTS_JSON" ]; then
    jq -r '
        .[] |
        select(.name == "USDFC" or .name == "Multicall3") |
        "\(.name | ascii_upcase)_ADDRESS=\(.address)"
    ' "$WORKSPACE_DEPLOYMENTS_JSON"
fi
echo ""

# Accounts
echo "# Accounts"
if [ -f "$ACCOUNTS_JSON" ]; then
    # Deployer private key
    DEPLOYER_KEY=$(jq -r '.accounts.deployer.privateKey // empty' "$ACCOUNTS_JSON")
    if [ -n "$DEPLOYER_KEY" ]; then
        echo "DEPLOYER_PRIVATE_KEY=$DEPLOYER_KEY"
    fi

    # Deployer ETH address
    DEPLOYER_ETH=$(jq -r '.accounts.deployer.ethAddress // empty' "$ACCOUNTS_JSON")
    if [ -n "$DEPLOYER_ETH" ]; then
        echo "DEPLOYER_ETH_ADDRESS=$DEPLOYER_ETH"
    fi
fi
echo ""
} > "$OUTPUT"

echo "✓ Environment exported to $OUTPUT"
